version: '3.7'
services:
  builder:
    build: ./builder
    volumes:
       - share:/build
  web:
    image: tomcat:8.5-alpine
    depends_on:
      - builder
    ports:
        - '8081:8080'
    volumes:
        -  share:/usr/local/tomcat/webapps/
volumes:
  share: {}