version: '3.8'
services:
  builder:
    container_name: builder
    build: builder
    volumes:
       - build:/App42PaaS-Java-MySQL-Sample/target/
  db:
    container_name: 'db'
    image: mysql:5.7
    ports: 
      - '3306:3306'
    network_mode: host
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mydb
      MYSQL_HOST: localhost
  web:
    container_name: 'web'
    build: web
    links:
      - db
    depends_on:
      - builder
      - db
    ports:
        - '8081:8080'
    volumes:
        - build:/usr/local/tomcat/webapps/:ro
        - build:/usr/local/tomcat/ROOT/:ro
volumes:
  build: {}
  db_data:
